# Generated by Django 6.0.2 on 2026-08-25 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_prospect_converted_client'),
        ('events', '0004_homephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='events.event'),
        ),
    ]
