  backend:
    build:
      context: ../innovevents-back
      dockerfile: ../innovevents-docker/docker/Dockerfile-backend
    container_name: innovevents_backend
    environment:
      DEBUG: "${DJANGO_DEBUG:-1}"
      SECRET_KEY: "${DJANGO_SECRET_KEY:-dev-only-change-me}"
      ALLOWED_HOSTS: "${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1}"
      DATABASE_URL: "postgres://${POSTGRES_USER:-innovevents}:${POSTGRES_PASSWORD:-innovevents_pwd}@db:5432/${POSTGRES_DB:-innovevents}"
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS:-http://localhost:5173,http://127.0.0.1:5173}"
      CSRF_TRUSTED_ORIGINS: "${CSRF_TRUSTED_ORIGINS:-}"

      # ✅ Superuser auto
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME:-admin}"
      DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL:-admin@innovevents.local}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD:-1234}"

    command: >
      sh -c "python manage.py migrate --noinput
      && python scripts/create_superuser.py
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ../innovevents-back:/app
    depends_on:
      db:
        condition: service_healthy
