services:
  db:
    image: postgres:16
   
    environment:
      POSTGRES_DB: innovevents
      POSTGRES_USER: innovevents
      POSTGRES_PASSWORD: innovevents_pwd
    ports:
      - "5433:5433"
    volumes:
      - innovevents_pgdata:/var/lib/postgresql/data

volumes:
  innovevents_pgdata:
