# Generated by Django 6.0.2 on 2026-04-11 14:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='client_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('SEMINAR', 'Séminaire'), ('CONFERENCE', 'Conférence'), ('PARTY', "Soirée d'entreprise"), ('OTHER', 'Autre')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACCEPTED', 'Accepté'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
