# Generated by Django 6.0.2 on 2026-08-16 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_client_event_client_agreed_event_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
    ]
