# Generated by Django 6.0.2 on 2026-06-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='validated',
        ),
    ]
