# Generated by Django 6.0.2 on 2026-08-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='event',
        ),
    ]
