# Generated by Django 6.0.2 on 2026-08-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='purpose',
            field=models.CharField(choices=[('EMAIL_VERIFICATION', 'Vérification e-mail'), ('PASSWORD_RESET', 'Réinitialisation du mot de passe'), ('LOGIN_2FA', 'Authentification à deux facteurs')], max_length=30),
        ),
    ]
