# Generated by Django 6.0.2 on 2026-08-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_verificationcode_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='purpose',
            field=models.CharField(choices=[('EMAIL_VERIFICATION', 'Vérification e-mail'), ('PASSWORD_RESET', 'Réinitialisation du mot de passe'), ('LOGIN_2FA', 'Authentification à deux facteurs'), ('ACCOUNT_ACTIVATION', 'Activation du compte')], max_length=30),
        ),
    ]
