# Generated by Django 6.0.2 on 2026-04-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='desired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='event_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prospect',
            name='participant_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
