-- =====================================================================
-- Innov'Events
-- Script SQL manuel de création du schéma métier PostgreSQL
--
-- Usage :
--   - Livrable documentaire et pédagogique
--   - À exécuter uniquement sur une base PostgreSQL vide de démonstration
--   - Ne pas exécuter sur une base déjà initialisée par les migrations Django
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. Utilisateurs
-- ---------------------------------------------------------------------

CREATE TABLE accounts_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    password VARCHAR(128) NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE NULL,
    is_superuser BOOLEAN NOT NULL DEFAULT FALSE,
    username VARCHAR(150) NOT NULL,
    first_name VARCHAR(150) NOT NULL DEFAULT '',
    last_name VARCHAR(150) NOT NULL DEFAULT '',
    email VARCHAR(254) NOT NULL DEFAULT '',
    is_staff BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    date_joined TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    role VARCHAR(20) NOT NULL DEFAULT 'CLIENT',
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_accounts_user
        PRIMARY KEY (id),

    CONSTRAINT uq_accounts_user_username
        UNIQUE (username),

    CONSTRAINT ck_accounts_user_role
        CHECK (role IN ('ADMIN', 'EMPLOYEE', 'CLIENT'))
);

COMMENT ON TABLE accounts_user IS
    'Comptes utilisateurs de l''application Innov''Events.';

COMMENT ON COLUMN accounts_user.password IS
    'Hash du mot de passe généré par Django.';

COMMENT ON COLUMN accounts_user.role IS
    'Rôle métier : ADMIN, EMPLOYEE ou CLIENT.';


-- ---------------------------------------------------------------------
-- 2. Prospects
-- ---------------------------------------------------------------------

CREATE TABLE crm_prospect (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    email VARCHAR(254) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    company VARCHAR(120) NOT NULL DEFAULT '',
    city VARCHAR(120) NOT NULL,
    message TEXT NOT NULL,
    event_type VARCHAR(50) NOT NULL DEFAULT '',
    desired_date DATE NULL,
    participant_count INTEGER NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'TO_CONTACT',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_crm_prospect
        PRIMARY KEY (id),

    CONSTRAINT ck_crm_prospect_participant_count
        CHECK (
            participant_count IS NULL
            OR participant_count >= 1
        ),

    CONSTRAINT ck_crm_prospect_status
        CHECK (
            status IN (
                'TO_CONTACT',
                'CONTACTED',
                'QUALIFIED',
                'ARCHIVED'
            )
        )
);

COMMENT ON TABLE crm_prospect IS
    'Demandes commerciales provenant de personnes sans compte client obligatoire.';


-- ---------------------------------------------------------------------
-- 3. Profils clients
-- ---------------------------------------------------------------------

CREATE TABLE crm_clientprofile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    company VARCHAR(120) NOT NULL DEFAULT '',
    phone VARCHAR(30) NOT NULL DEFAULT '',
    address VARCHAR(255) NOT NULL DEFAULT '',

    CONSTRAINT pk_crm_clientprofile
        PRIMARY KEY (id),

    CONSTRAINT uq_crm_clientprofile_user
        UNIQUE (user_id),

    CONSTRAINT fk_crm_clientprofile_user
        FOREIGN KEY (user_id)
        REFERENCES accounts_user(id)
        ON DELETE CASCADE
);

COMMENT ON TABLE crm_clientprofile IS
    'Informations complémentaires associées à un utilisateur client.';


-- ---------------------------------------------------------------------
-- 4. Événements
-- ---------------------------------------------------------------------

CREATE TABLE events_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    city VARCHAR(120) NOT NULL,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NULL,
    capacity INTEGER NOT NULL DEFAULT 1,
    event_type VARCHAR(20) NOT NULL DEFAULT 'OTHER',
    theme VARCHAR(120) NOT NULL DEFAULT '',
    image VARCHAR(100) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    visible BOOLEAN NOT NULL DEFAULT FALSE,
    client_agreed BOOLEAN NOT NULL DEFAULT FALSE,
    organizer_id BIGINT NOT NULL,
    client_id BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_events_event
        PRIMARY KEY (id),

    CONSTRAINT fk_events_event_organizer
        FOREIGN KEY (organizer_id)
        REFERENCES accounts_user(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_events_event_client
        FOREIGN KEY (client_id)
        REFERENCES accounts_user(id)
        ON DELETE SET NULL,

    CONSTRAINT ck_events_event_capacity
        CHECK (capacity >= 1),

    CONSTRAINT ck_events_event_dates
        CHECK (
            end_at IS NULL
            OR end_at > start_at
        ),

    CONSTRAINT ck_events_event_type
        CHECK (
            event_type IN (
                'SEMINAR',
                'CONFERENCE',
                'PARTY',
                'OTHER'
            )
        ),

    CONSTRAINT ck_events_event_status
        CHECK (
            status IN (
                'DRAFT',
                'ACCEPTED',
                'IN_PROGRESS',
                'DONE',
                'CANCELLED'
            )
        )
);

COMMENT ON TABLE events_event IS
    'Événements organisés par Innov''Events.';


-- ---------------------------------------------------------------------
-- 5. Réservations
-- ---------------------------------------------------------------------

CREATE TABLE bookings_booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_bookings_booking
        PRIMARY KEY (id),

    CONSTRAINT fk_bookings_booking_user
        FOREIGN KEY (user_id)
        REFERENCES accounts_user(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_bookings_booking_event
        FOREIGN KEY (event_id)
        REFERENCES events_event(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_bookings_booking_quantity
        CHECK (quantity >= 1),

    CONSTRAINT ck_bookings_booking_status
        CHECK (
            status IN (
                'PENDING',
                'CONFIRMED',
                'CANCELLED'
            )
        )
);

COMMENT ON TABLE bookings_booking IS
    'Réservations réalisées par les utilisateurs pour les événements.';


-- ---------------------------------------------------------------------
-- 6. Devis
-- ---------------------------------------------------------------------

CREATE TABLE crm_quote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    client_id BIGINT NULL,
    prospect_id BIGINT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    tva_rate NUMERIC(5,2) NOT NULL DEFAULT 0.20,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_crm_quote
        PRIMARY KEY (id),

    CONSTRAINT fk_crm_quote_client
        FOREIGN KEY (client_id)
        REFERENCES accounts_user(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_crm_quote_prospect
        FOREIGN KEY (prospect_id)
        REFERENCES crm_prospect(id)
        ON DELETE SET NULL,

    CONSTRAINT ck_crm_quote_status
        CHECK (
            status IN (
                'DRAFT',
                'SENT',
                'ACCEPTED',
                'REFUSED',
                'CHANGE_REQUESTED'
            )
        ),

    CONSTRAINT ck_crm_quote_tva_rate
        CHECK (tva_rate >= 0),

    CONSTRAINT ck_crm_quote_recipient
        CHECK (
            (client_id IS NOT NULL AND prospect_id IS NULL)
            OR
            (client_id IS NULL AND prospect_id IS NOT NULL)
        )
);

COMMENT ON TABLE crm_quote IS
    'Devis adressés à un utilisateur client ou à un prospect.';

COMMENT ON COLUMN crm_quote.tva_rate IS
    'Taux de TVA sous forme décimale : 0.20 représente 20 %.';


-- ---------------------------------------------------------------------
-- 7. Lignes de devis
-- ---------------------------------------------------------------------

CREATE TABLE crm_quoteitem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    quote_id BIGINT NOT NULL,
    label VARCHAR(200) NOT NULL,
    amount_ht NUMERIC(10,2) NOT NULL,

    CONSTRAINT pk_crm_quoteitem
        PRIMARY KEY (id),

    CONSTRAINT fk_crm_quoteitem_quote
        FOREIGN KEY (quote_id)
        REFERENCES crm_quote(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_crm_quoteitem_amount_ht
        CHECK (amount_ht >= 0)
);

COMMENT ON TABLE crm_quoteitem IS
    'Lignes composant les devis.';


-- ---------------------------------------------------------------------
-- 8. Notes internes
-- ---------------------------------------------------------------------

CREATE TABLE crm_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author_id BIGINT NOT NULL,
    client_id BIGINT NULL,
    content TEXT NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_crm_note
        PRIMARY KEY (id),

    CONSTRAINT fk_crm_note_author
        FOREIGN KEY (author_id)
        REFERENCES accounts_user(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_crm_note_client
        FOREIGN KEY (client_id)
        REFERENCES accounts_user(id)
        ON DELETE SET NULL
);

COMMENT ON TABLE crm_note IS
    'Notes internes rédigées au sujet des clients.';


-- ---------------------------------------------------------------------
-- 9. Avis
-- ---------------------------------------------------------------------

CREATE TABLE reviews_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author_id BIGINT NOT NULL,
    rating SMALLINT NOT NULL DEFAULT 5,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_reviews_review
        PRIMARY KEY (id),

    CONSTRAINT fk_reviews_review_author
        FOREIGN KEY (author_id)
        REFERENCES accounts_user(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_reviews_review_rating
        CHECK (rating BETWEEN 1 AND 5)
);

COMMENT ON TABLE reviews_review IS
    'Avis publiés par les utilisateurs.';


-- ---------------------------------------------------------------------
-- 10. Index
-- ---------------------------------------------------------------------

CREATE INDEX idx_crm_prospect_status
    ON crm_prospect(status);

CREATE INDEX idx_crm_prospect_created_at
    ON crm_prospect(created_at);

CREATE INDEX idx_events_event_start_at
    ON events_event(start_at);

CREATE INDEX idx_events_event_status
    ON events_event(status);

CREATE INDEX idx_events_event_organizer_id
    ON events_event(organizer_id);

CREATE INDEX idx_events_event_client_id
    ON events_event(client_id);

CREATE INDEX idx_bookings_booking_user_id
    ON bookings_booking(user_id);

CREATE INDEX idx_bookings_booking_event_id
    ON bookings_booking(event_id);

CREATE INDEX idx_crm_quote_client_id
    ON crm_quote(client_id);

CREATE INDEX idx_crm_quote_prospect_id
    ON crm_quote(prospect_id);

CREATE INDEX idx_crm_quote_status
    ON crm_quote(status);

CREATE INDEX idx_crm_quoteitem_quote_id
    ON crm_quoteitem(quote_id);

CREATE INDEX idx_crm_note_author_id
    ON crm_note(author_id);

CREATE INDEX idx_crm_note_client_id
    ON crm_note(client_id);

CREATE INDEX idx_reviews_review_author_id
    ON reviews_review(author_id);

CREATE INDEX idx_reviews_review_created_at
    ON reviews_review(created_at DESC);

COMMIT;